Restoring the default parameter for now because of usage in `system-contracts` repo.
```
/__w/spring/spring/system-contracts/tests/eosio.system_tester.hpp:1553:18: error: no matching function for call to 'eosio::chain::signed_transaction::sign(fc::crypto::private_key, eosio::chain::chain_id_type)'
2440
 1553 |          trx.sign( get_private_key( "producer1111"_n, "active" ), control->get_chain_id()  );
2441
      |          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```